name: Test Tomato App

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: |
          cd backend
          npm install
      - run: |
          cd backend
          cat > .env << EOF
          PORT=${{ vars.PROD_PORT }}
          DB_URI=${{ vars.PROD_DB_URI }}
          WEB_CLIENT_ID=${{ secrets.WEB_CLIENT_ID }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          WSS_PORT=${{ vars.WSS_PORT }} 
          EOF
          npm test