name: Test Tomato App

on:
  push:
    branches: [main]
  pull_request:
    branches: [ main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v2

      # Setup Node
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        working-directory: backend
        run: npm install

      # Set up .env file for dotenv
      - name: Set environment variables
        working-directory: backend
        run: |
          cat > .env <<EOF
          PORT=${{ vars.PROD_PORT }}
          DB_URI=${{ vars.PROD_DB_URI }}
          WEB_CLIENT_ID=${{ secrets.WEB_CLIENT_ID }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          WSS_PORT=${{ vars.WSS_PORT }}
          EOF

      # Run tests with coverage
      - name: Run tests with coverage
        working-directory: backend
        run: npx jest --coverage

      # Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Only needed if repo is private
          files: ./backend/coverage/lcov.info
          flags: unittests
          name: tomato-backend-report
          fail_ci_if_error: true
