name: Test Tomato App

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PORT: ${{ vars.PORT }}
      DB_URI: ${{ secrets.DB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      WSS_PORT: ${{ vars.PORT }}
    steps:
      - run: npm test
